# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vm.box = "resmas/dockerlab"
  #config.vm.box_version = "1.0.1"
  #config.vm.box = "ubuntu-18.04-amd64-virtualbox"
  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false
  config.ssh.insert_key = false

  config.vm.hostname= "ubuntu-docker"
  #config.disksize.size = "30GB"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.11"
  # config.vm.network "public_network"

  config.vm.synced_folder "../", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true

     vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y docker.io
    usermod -aG docker vagrant
  SHELL
end
