version: '3'

services:
  mariadb:
    image: mariadb
    volumes:
      - /data/db/docker/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      labels: [APP=mariadb]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == manager1]
        
  php-fpm:
    image: gvergne/php-fpm-mysql
    volumes:
      - /Users/gv/www:/var/www/html:ro
      - /Users/gv/dev/docker/compose/nginx-php-mariadb/conf/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - mariadb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      labels: [APP=php-fpm]
      restart_policy:
        condition: on-failure

  nginx-php:
    image: nginx:alpine
    volumes:
      - /Users/gv/www:/usr/share/nginx/html:ro
      - /Users/gv/dev/docker/compose/nginx-php-mariadb/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mariadb
      - php-fpm
    ports:
      - 82:80
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      labels: [APP=nginx-php]
      restart_policy:
        condition: on-failure