
---

apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: policy
  namespace: istio-system
spec:
  targets:
    - name: istio-ingressgateway
  peers:
    - mtls: {}
  origins:
    - jwt:
        issuer: "http://keycloak.192.168.64.10.nip.io/auth/realms/istio"
        jwksUri: "http://keycloak.192.168.64.10.nip.io/auth/realms/istio/protocol/openid-connect/certs"
  principalBinding: USE_ORIGIN
