---

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: ubuntu-debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- include_tasks: openbsd.yml
  when: ansible_distribution == 'OpenBSD'