version: '2'

services:
  kibana:
    image: kibana:5.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5.0.0
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /data/db/docker/elasticsearch-5.0:/usr/share/elasticsearch/data
