---

#Linux amd64
#https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz
- name: "Download package"
  get_url:
    url: https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz
    dest: /tmp

- name: Extract
  unarchive:
    src: /tmp/helm-v2.11.0-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy bin
  shell: cp /tpm/linux-amd64/helm /usr/local/bin
  args:
    creates: /usr/local/bin/helm