---

- name: "Templating ingress service yml"
  template:
    src: ingress-nginx-service-nodeport.yaml
    dest: $HOME/ingress-nginx-service-nodeport.yaml
  #register: ingress_service

- name: "Install ingress controller"
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/namespace.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/default-backend.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/configmap.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/tcp-services-configmap.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/udp-services-configmap.yaml

    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/rbac.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/with-rbac.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/baremetal/service-nodeport.yaml

    kubectl apply -f $HOME/ingress-nginx-service-nodeport.yaml

    touch $HOME/ingress-controller.initialized
  args:
    creates: ingress-controller.initialized
  #changed_when: ingress_service is changed
