version: '2'

services:
  postgresql-master:
    image: postgresql
    environment:
      - POSTGRES_INIT_DB=true
      - POSTGRES_REPLICATION_NETWORK=0.0.0.0/0
      - POSTGRES_WAL_LEVEL=hot_standby
      - POSTGRES_MAX_WAL_SENDERS=3
      - POSTGRES_CHECKPOINT_SEGMENTS=8
      - POSTGRES_WAL_KEEP_SEGMENTS=8
      - POSTGRES_SLAVE_IP=0.0.0.0
      - POSTGRES_REPLICATION_TYPE=master

  postgresql-slave:
    image: postgresql
    environment:
      - POSTGRES_WAL_LEVEL=hot_standby
      - POSTGRES_MAX_WAL_SENDERS=3
      - POSTGRES_CHECKPOINT_SEGMENTS=8
      - POSTGRES_WAL_KEEP_SEGMENTS=8
      - POSTGRES_HOT_STANDBY=on
      - POSTGRES_REPLICATE_FROM_IP=postgresql-master
      - POSTGRES_REPLICATE_FROM_PORT=5432
      - POSTGRES_REPLICATION_TYPE=slave
      - POSTGRES_REPLICATOR_USER=replicator
      - POSTGRES_REPLICATOR_PASSWORD=replicator
    links:
      - postgresql-master

  pgpool:
    image: pgpool
    ports:
      - "9999:9999"
    links:
      - postgresql-master
      - postgresql-slave
    volumes:
      - /Users/gv/dev/docker/pgpool/conf/backends.conf:/tmp/backends.conf:ro