version: '2'

services:
  postgresql-master:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - ./init-master.sh:/docker-entrypoint-initdb.d/init-user-db.sh
        - /data/db/docker/postgresql:/var/lib/postgresql/data
