version: '3'

services:

  postgres:
    image: postgres
    restart: unless-stopped
    #ports:
    #  - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_ROOT_PASSWORD=postgres
    volumes:
      -  ~/data/db/docker/keycloak/postgresql:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_ADDR=postgres
      - DB_PORT=5432
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=INFO #DEBUG
    #depends_on:
    #  - postgres
    #links:
    #  - postgres:postgres