version: '2'

services:
  postgresql-sonar:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /data/db/docker/postgresql-sonar:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  sonarcube:
    image: sonarqube:alpine
    ports:
      - "9000:9000"
      - "9092:9092"
    depends_on:
      - postgresql-sonar
    links:
      - postgresql-sonar:postgresql
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar