---

- name: Add ssh port forward
  template:
    src: ssh_forward
    dest: /etc/xinetd.d/ssh_forward
  register: ssh_forward_created

- name: Add container port forward
  template:
    src: container_forward
    dest: /etc/xinetd.d/container_forward
  register: container_forward_created

- name: Restart xinetd
  service:
    name: xinetd
    state: restarted
  when: (ssh_forward_created is changed) or (container_forward_created is changed)