---

- debug:
    msg: "X11 FreeBSD"

#/etc/pkg/FreeBSD.conf
#- name: "change pkg repository"
#  template:
#    src: FreeBSD.conf
#    dest: /etc/pkg/FreeBSD.conf

#- command: "pkg update"
#- command: "pkg upgrade -y"

- name: Install Dependencies
  pkgng:
    name: [
      'vim'
    ]
    state: present