---

- name: Install Common
  package:
    name: [
      'python',
      #'python3-apt'
    ]
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or  ansible_distribution == 'CentOS'


- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- include_tasks: openbsd.yml
  when: ansible_distribution == 'OpenBSD'

- include_tasks: debian-ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#- name: Add locale gen file
#  template:
#    src: locale.gen
#    dest: /etc/locale.gen
#
#- name: Update locales
#  shell: |
#    locale-gen
#    dpkg-reconfigure locales -f noninteractive

#- name: Wait for automatic system updates
#  become: true
#  shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
#  with_items:
#    - lock
#    - lock-frontend

- name: Install Common
  package:
    name: [
      'vim',
      'git',
      'curl',
      'wget',
      'net-tools',
      'xinetd',
      'htop',
      'psmisc',
      'iputils-*',
      #'snap', 'snapd'
    ]
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or  ansible_distribution == 'CentOS'

# linux
# localectl list-keymaps
# localectl set-keymap fr-mac
- name: "Set keyboard layout"
  shell: |
    localectl set-keymap fr-ma
    localectl set-x11-keymap fr macintosh
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or  ansible_distribution == 'CentOS'

# openbsd
# wsconsctl -w keyboard.encoding=fr
# echo "fr" > /etc/kbdtype

- name: "FR Keyboard"
  lineinfile:
    path: /etc/kbdtype
    line: fr
    create: yes
  when: ansible_distribution == 'OpenBSD'

# freebsd
# echo 'keymap="fr"' >> /etc/rc.conf

- name: "FR Keyboard"
  lineinfile:
    path: /etc/rc.conf
    line: 'keymap="fr"'
  when: ansible_distribution == 'FreeBSD'

# sudo timedatectl set-timezone Europe/Paris
- name: "Change timezone"
  shell: timedatectl set-timezone Europe/Paris
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or  ansible_distribution == 'CentOS'

# OpenBsd
# # zic -l Europe/Paris

# FreeBsd
# tzsetup /usr/share/zoneinfo/Europe/Paris
