version: 1
config:
- type: physical
  name: eth0
  subnets:
  - type: static
    ipv4: true
    address: 10.253.106.243
    netmask: 255.255.255.0
    gateway: 10.253.106.1
    control: auto
- type: nameserver
  address: 10.253.106.1