---

- hosts:
  - lxc-ubuntu
  - lxc-masters
  remote_user: root
  roles:
    - helm
  become: yes

- hosts: lxc-ubuntu
  vars:
    k8s_dashboard_port: 31223
    k8s_dashboard_hostname: dashboard.192.168.33.15.nip.io
    k8s_ingress_external_ips:
    - 10.0.4.100
    - 10.0.4.110
    #- 10.0.4.111
  roles:
  - kubernetes-modules