---

- hosts: kubernetes-ubuntu
  remote_user: root
  vars:
    k8s_master_node: kubernetes-ubuntu
    k8s_apiserver_advertise_address: "192.168.33.16"
    k8s_apiserver_cert_extra_sans: "192.168.33.16"
    k8s_ingress_external_ips: [192.168.33.16]
    k8s_dashboard_port: 31223
    k8s_dashboard_hostname: "dashboard.192.168.33.16.nip.io"
  roles:
    - common
    - disk-utils
    - docker
    - kubernetes
    - kubernetes-config
    - kubernetes-modules
  become: yes
