# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vm.box = "ubuntu-18.10-amd64-virtualbox"
  #config.vm.box = "ubuntu-kubernetes"
  config.vm.box = "ubuntu-kubernetes-istio-rook"

  config.vm.hostname= "kubernetes-ubuntu"
  config.disksize.size = "50GB"

  config.vm.box_check_update = false
  config.ssh.insert_key = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.33.16"

  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "8000"
      vb.cpus = "8"
  end

  #config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt install -y python
  #   apt-get install -y apache2
  #SHELL

  config.vm.provision "install", run: "never", type: "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
