version: '2'

services:
  mongodb-express:
    image: mongo-express:0.31.5
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    links:
      - mongodb:mongo

  mongodb:
    image: mongo:3.2.10
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /data/db/docker/mongodb/data/db:/data/db
      - /data/db/docker/mongodb/data/configdb:/data/configdb