# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vm.box = "freebsd-12.0-amd64-virtualbox"
  config.vm.box = "openbsd-6.4-amd64-virtualbox"

  config.vm.hostname = 'bsd-server'

  config.ssh.shell = "sh"

  config.disksize.size = "50GB"

  #config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.network "public_network"

  #config.vm.synced_folder "../data", "/vagrant_data"
  #config.vm.synced_folder "/Users/gv/dev", "/vagrant_data"
  config.vm.synced_folder ".", "/vagrant", disabled: true


  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
  end

  config.vm.provision "install", run: "never", type: "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
