---

- name: Remove swapfile from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(/swapfile*)'
    replace: '#\1'

#  mount:
#    name: swap
#    fstype: swap
#    state: absent

- name: Disable swap
  command: swapoff -a
  #when: ansible_swaptotal_mb > 0

- name: Add Kubernetes GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"

- name: Install Kubernetes
  package:
    name: "{{ item }}"
  with_items:
    - xfsprogs
    #- kubernetes-cni
    - kubelet
    - kubeadm
    - kubectl

- name: "enable kubelet"
  systemd:
    name: kubelet
    enabled: yes