version: '2'

services:
  kibana:
    image: kibana:4.6.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:2.4.1
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /data/db/docker/elasticsearch:/usr/share/elasticsearch/data
