---

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_pgp_key }}"
    validate_certs: false

- name: Add Docker APT repository
  apt_repository:
    repo: "{{ docker_repo }}"

- name: Install Docker
  package:
    name: "{{item}}"
  with_items:
    - docker-ce
    - docker-compose
  #register: docker_installed

- name: Add docker insecure registry
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  register: docker_installed

#- name: Open Docker socket
#  lineinfile:
#    path: /etc/default/docker
#    line: 'DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"'
#    create: no
#  when: docker_open_socket

- name: Restart docker
  service:
    name: docker
    state: restarted
  when: docker_installed is changed

- name: "Download dive"
  get_url:
    url: https://github.com/wagoodman/dive/releases/download/v0.7.2/dive_0.7.2_linux_amd64.deb
    dest: /tmp
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Install dive"
  apt:
    deb: /tmp/dive_0.7.2_linux_amd64.deb
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# groupadd docker
# usermod -aG docker vagrant

- name: "Fix error on docker build"
  shell: dpkg -r --force-depends golang-docker-credential-helpers
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "adding vagrant to docker group"
  user:
    name: 'vagrant'
    groups: docker
    append: yes