---


# wget -O /etc/yum.repos.d/ambari.repo http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.5.1.0/ambari.repo
# yum install ambari-server -y

# wget http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.1.0/hdp.repo -O /etc/yum/hdp.repo
# http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.1.0/ambari.repo -O /etc/yum.repos.d/ambari.repo

# yum-config-manager --add-repo http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.1.0/hdp.repo
# yum-config-manager --add-repo http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.5.1.0/ambari.repo

- name: "etc hosts"
  template:
    src: hosts
    dest: /etc/hosts

# make ssh work localhost

- name: "Copy ssh key"
  copy:
    src: private_key
    dest: /home/vagrant/.ssh/ir_rsa
    owner: vagrant
    group: vagrant
    mode: '0600'

- name: "Disable selinux"
  command: setenforce 0

# disable iptable
# systemctl stop firewalld
# systemctl disable firewalld
- name: "Disable FirewalldD"
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Install Common
  package:
    name: [
      'ntp',
    ]
    state: present

- name: "Start NTPD"
  systemd:
    name: ntpd
    state: started
    enabled: yes

- name: "Download Ambari repo"
  get_url:
    url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.3.0/ambari.repo
    dest: /etc/yum.repos.d/ambari.repo
