# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vm.box = "generic/ubuntu1810"
  #config.vm.box = "ubuntu-budgie"
  #config.vm.box = "debian-desktop-base"
  #config.vm.box = "ubuntu-lxqt"
  #config.vm.hostname= "debian-desktop"

  config.vm.box = "ubuntu-18.10-amd64-virtualbox"
  #config.vm.box = "debian-9.8-amd64-virtualbox"

  config.disksize.size = "50GB"

  # config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.network "public_network"

  config.vm.synced_folder "/data", "/vagrant"
  config.vm.synced_folder "/Users/gv/dev", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true

     vb.memory = "2048"
     vb.cpus = "4"

     # Set the video memory to 128Mb:
     vb.customize ["modifyvm", :id, "--vram", "128"]

     # Enable 2D acceleration:
     vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]

     # Enable 3D acceleration:
     vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end

  config.vm.provision "install", run: "never", type: "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
