# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vm.box = "generic/ubuntu1810"

  #config.vm.box = "netbsd-desktop"
  #config.vm.box = "openbsd-desktop"
  config.vm.box = "freebsd-desktop"

  #config.vm.hostname= "bsd-desktop"
  config.disksize.size = "50GB"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  #config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.cpus = "4"

     # Set the video memory to 128Mb:
     vb.customize ["modifyvm", :id, "--vram", "128"]

     # Enable 2D acceleration:
     #vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]

     # Enable 3D acceleration:
     #vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end

  #config.vm.provision "ansible" do |ansible|
  #    ansible.playbook = "playbook.yml"
  #end
end
