# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "freebsd-12.0-amd64-virtualbox"
  #config.vm.box = "openbsd-6.4-amd64-virtualbox"

  #config.vm.hostname= "bsd-desktop"
  config.disksize.size = "50GB"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.synced_folder ".", "/vagrant", type: "rsync"

  #config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true

     vb.memory = "2048"
     vb.cpus = "4"

     vb.customize ["modifyvm", :id, "--vram", "128"]
     #vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
     #vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end

  config.vm.provision "install", run: "never", type: "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
