version: '3'

services:
  nginx:
    ports:
      - 81:80
    image: gvergne/nginx-static
    volumes:
      - /Users/gv/www:/usr/share/nginx/html:ro
      - /Users/gv/dev/docker/compose/web-static/default.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      labels: [APP=web-static]
      restart_policy:
        condition: on-failure
      
          