---

- name: Install Common
  package:
    name: "parted"

- name: Install common Centos
  package:
    name:
      - cloud-utils-growpart
  when: ansible_distribution == 'CentOS'

- name: Install common
  package:
    name:
      - cloud-guest-utils
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: resize-partition.yml

- shell:  df -H | grep {{ disk }}
  register: disk_space

- debug:
    msg: "{{ disk_space.stdout }}"