version: '2'

services:
  emby:
    image: emby/embyserver
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359/udp:7359/udp"
      - "1900/udp:1900/udp"
    restart: unless-stopped
    volumes:
      - /data/db/docker/emby:/config
      - /data/p2p:/data/media/video
      - /Users/gv/Pictures/autre:/data/media/photo
